// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace SRGameplayTags
{

SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Grapple);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);

SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTag_Jump);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTag_Dash);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTag_Grapple);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTag_Attack);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTag_Death);
SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTag_Shoot);

SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EventTag_AttackWindow);

SLICERUNNER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EventTag_AttackState);



} // namespace SRGameplayTags
